CREATE TABLE USER (ID BIGINT AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(255), LAST_NAME VARCHAR(255), EMAIL VARCHAR(255));

CREATE TABLE INGREDIENTS (ID INT PRIMARY KEY, NAME VARCHAR(50), DESCRIPTION VARCHAR(255));

CREATE TABLE RECIPES (ID INT PRIMARY KEY, NAME VARCHAR(50), DESCRIPTION VARCHAR(255), TYPE_ID INT);

CREATE TABLE RECIPE_TYPES (ID INT PRIMARY KEY, NAME VARCHAR(50));

CREATE TABLE RECIPE_INGREDIENTS (RECIPE_ID INT, INGREDIENT_ID INT, VOLUME VARCHAR(50));