package org.lanyonm.grabbag.persistence;

import java.util.List;

import org.lanyonm.grabbag.domain.Ingredient;

/**
 * Mybatis mappers are autogenerated.  Put any special sauce in the service layer.
 * 
 * @author lanyonm
 */
public interface IngredientMapper {

	public List<Ingredient> getAllIngredients();
	public Ingredient getIngredient(int id);
	public int updateIngredient(Ingredient ingredient);
	public int insertIngredient(Ingredient ingredient);
	public Integer deleteIngredient(Ingredient ingredient);

}
