package org.lanyonm.grabbag.persistence;

import java.util.List;

import org.lanyonm.grabbag.domain.Recipe;

/**
 * Mybatis mappers are autogenerated.  Put any special sauce in the service layer.
 * 
 * @author lanyonm
 */
public interface RecipeMapper {

	public List<Recipe> getAllRecipes();
	public Recipe getRecipe(int id);
	public int updateRecipe(Recipe recipe);
	public int insertRecipe(Recipe recipe);
}
